// BlueprintGeneratedClass BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C
// Size: 0x1688 (Inherited: 0x1670)
struct ABP_DB_Lightweight_Character_C : ABiped_Lightweight {
	struct FPointerToUberGraphFrame UberGraphFrame; // 0x1670(0x08)
	struct UAnimationComponent* Animation; // 0x1678(0x08)
	struct UCustomizableCharacterComponent* CustomizableCharacter; // 0x1680(0x08)

	struct UCurveFloat* GetSpeedGovernorCurve(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetSpeedGovernorCurve // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetAutoTargetFocusDirection(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetAutoTargetFocusDirection // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetAutoTargetUpDirection(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetAutoTargetUpDirection // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetToTargetDirection(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetToTargetDirection // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void CalculateClimbingLedgeState(enum class EClimbingLedgeState& OutState, enum class EJumpingType& OutType); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.CalculateClimbingLedgeState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector CalculateLookAtDirection(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.CalculateLookAtDirection // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	float ComputeAngleToDesiredDirection(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ComputeAngleToDesiredDirection // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ComputeAttack(struct AActor*& TargetActor); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ComputeAttack // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ComputeReaction(struct FVector HitLocation, struct FVector TraceDirection, struct FString OverrideName, enum class EReactionState& ReactionState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ComputeReaction // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetAdditiveBodyState(enum class EAdditiveBodyState& OutState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetAdditiveBodyState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct AActor* GetBestAutoTargetActor(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetBestAutoTargetActor // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetBestAutoTargetActor_WorldLocation(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetBestAutoTargetActor_WorldLocation // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct AActor* GetBestLockOnActor(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetBestLockOnActor // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetBestLockOnActor_ScreenLocation(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetBestLockOnActor_ScreenLocation // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetBestLockOnActor_WorldLocation(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetBestLockOnActor_WorldLocation // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetFullBodyState(enum class EFullBodyState& OutState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetFullBodyState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetFullBodyStateLast(enum class EFullBodyState& OutState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetFullBodyStateLast // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct AActor* GetHighlitActor(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetHighlitActor // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FInventoryResult GetInventoryResult(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetInventoryResult // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetParryState(enum class EParryState& OutState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetParryState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetPartialBodyState(enum class EPartialBodyState& OutState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetPartialBodyState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct APickupTool* GetPickupTool(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetPickupTool // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	float GetPickupToolHeight(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetPickupToolHeight // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	float GetPutdownToolHeight(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetPutdownToolHeight // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	enum class ERightArmState GetRightArmState(enum class ERightArmPriority InPriority); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetRightArmState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetRootMotionOffset(struct FVector& OutTranslationOffset); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetRootMotionOffset // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct USkeletalMeshComponent* GetSkeletalMesh(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetSkeletalMesh // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x38a7480
	struct UCurveFloat* GetSpeedCurve(bool& bIgnoreGovernor); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetSpeedCurve // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetSpellCastHandle(int32_t& OutSpellCastHandle); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetSpellCastHandle // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FName GetTargetBoneName(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetTargetBoneName // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct UPrimitiveComponent* GetTargetComponent(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetTargetComponent // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FVector GetTargetDestination(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetTargetDestination // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x38a7480
	struct FVector GetTargetDirection(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetTargetDirection // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct AWandTool* GetWand(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.GetWand // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x38a7480
	bool InLockOnMode(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.InLockOnMode // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	bool InstaUseInventoryItem(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.InstaUseInventoryItem // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	bool IsDead(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.IsDead // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	bool IsInReadyMode(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.IsInReadyMode // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct FName ParkourJump(struct FName DefaultNode); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ParkourJump // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	bool ProcessStick(float StickX, float StickY, float DeltaTime, struct UCurveFloat* DeadZoneCurve, struct UCurveFloat* SpeedCurve, struct UCurveFloat* SpeedGovernorCurve, float& WorldSpeed, struct FVector& WorldDirection, enum class ECustomInterpType InterpType, float InterpSpeed, float StickMagReductionDelayTimer); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ProcessStick // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	bool QuickActionInteract(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.QuickActionInteract // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RequestMove(float StickX, float StickY, float DeltaTime, float& Speed, float& Direction, float& LookAtDirection); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.RequestMove // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct AActor* SpawnFaceTarget(struct AActor* SpawnActorClass); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SpawnFaceTarget // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct AActor* SpawnLookAtTarget(struct AActor* SpawnActorClass); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SpawnLookAtTarget // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	struct APawn* SpawnStudent(struct ABiped_Character* StudentClass); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SpawnStudent // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ClearStick(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ClearStick // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void EquipWand(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.EquipWand // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void FlooStart(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.FlooStart // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void FullyResetPhoenixCamera(float ResetSpeed, struct UCurveFloat* ResetSpeedCurve); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.FullyResetPhoenixCamera // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void LockOnCameraMoving(bool bFlag); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.LockOnCameraMoving // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void LockOnCamFlick(struct UStickFlickWatcherRecord* InStickFlickWatcherRecord); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.LockOnCamFlick // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void LockOnToActor(struct AActor* InLockOnActor); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.LockOnToActor // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void PauseMenuStart(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.PauseMenuStart // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void PopDisableStack(struct FName_GameLogicVarInt32 StackName); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.PopDisableStack // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void PushDisableStack(struct FName_GameLogicVarInt32 StackName); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.PushDisableStack // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ReadyModeStart(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ReadyModeStart // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ReadyModeStop(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ReadyModeStop // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ReleasePhoenixCameraLookAt(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ReleasePhoenixCameraLookAt // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RequestStick(float StickX, float StickY); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.RequestStick // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ResetPhoenixCameraRotation(float ResetSpeed, struct UCurveFloat* ResetSpeedCurve); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ResetPhoenixCameraRotation // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetAdditiveBodyState(enum class EAdditiveBodyState& InState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetAdditiveBodyState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetFinisherOptimalRatio(float OptimalRatio, enum class EDynamicForceFeedbackAction FeedbackAction); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetFinisherOptimalRatio // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetFullBodyState(enum class EFullBodyState& InState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetFullBodyState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetFullBodyStateLast(enum class EFullBodyState& InState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetFullBodyStateLast // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetParryState(enum class EParryState& InState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetParryState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPartialBodyState(enum class EPartialBodyState& InState); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPartialBodyState // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPhoenixCameraLookAt(struct FVector& LookAtPoint, float ScaleSpeed); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPhoenixCameraLookAt // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPhoenixCameraLookAt_Actor(struct AActor* LookAtActor, float ScaleSpeed); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPhoenixCameraLookAt_Actor // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPhoenixCameraLookAt_ActorAndTime(struct AActor* LookAtActor, float LookAtTime); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPhoenixCameraLookAt_ActorAndTime // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPhoenixCameraLookAt_TimeBased(struct FVector& LookAtPoint, float LookAtTime); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPhoenixCameraLookAt_TimeBased // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPhoenixCameraRotation(struct FRotator& DesiredRotation); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPhoenixCameraRotation // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetPickupTool(struct APickupTool* InPickupTool); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetPickupTool // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetRightArmState(enum class ERightArmState InState, enum class ERightArmPriority InPriority, bool bBroadcastChange); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetRightArmState // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetRootMotionOffset(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetRootMotionOffset // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetRootMotionOffsets(struct FVector& TranslationOffset, struct FRotator& RotationOffset); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetRootMotionOffsets // (Event|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetSpellCastHandle(int32_t InSpellCastHandle); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.SetSpellCastHandle // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void StopMove(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.StopMove // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void UnEquipWand(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.UnEquipWand // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void UnLockOnToActor(); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.UnLockOnToActor // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void UseInventoryItemByName(struct FName InventoryObjectID); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.UseInventoryItemByName // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ExecuteUbergraph_BP_DB_Lightweight_Character(int32_t EntryPoint); // Function BP_DB_Lightweight_Character.BP_DB_Lightweight_Character_C.ExecuteUbergraph_BP_DB_Lightweight_Character // (Final|UbergraphFunction|HasDefaults) // @ game+0x38a7480
};

