// BlueprintGeneratedClass BP_FollowTargetRotationSpring_HippogriffFlight_Hover.BP_FollowTargetRotationSpring_HippogriffFlight_Hover_C
// Size: 0x218 (Inherited: 0x218)
struct UBP_FollowTargetRotationSpring_HippogriffFlight_Hover_C : UCameraStackBehaviorFollowTargetRotationSpring {
};

