// BlueprintGeneratedClass BP_SanctuaryPortal_MaterialComponent_GLNDToStudy_Particles.BP_SanctuaryPortal_MaterialComponent_GLNDToStudy_Particles_C
// Size: 0x320 (Inherited: 0x320)
struct UBP_SanctuaryPortal_MaterialComponent_GLNDToStudy_Particles_C : UBP_SanctuaryPortal_MaterialComponent_GLNDToStudy_C {
};

