// BlueprintGeneratedClass BP_SanctuaryPortal_MaterialComponent_StudyToFRST_Particles.BP_SanctuaryPortal_MaterialComponent_StudyToFRST_Particles_C
// Size: 0x320 (Inherited: 0x320)
struct UBP_SanctuaryPortal_MaterialComponent_StudyToFRST_Particles_C : UBP_SanctuaryPortal_MaterialComponent_StudyToFRST_C {
};

