// BlueprintGeneratedClass BP_SanctuaryPortal_MaterialComponent_COASTToStudy_Portal.BP_SanctuaryPortal_MaterialComponent_COASTToStudy_Portal_C
// Size: 0x320 (Inherited: 0x320)
struct UBP_SanctuaryPortal_MaterialComponent_COASTToStudy_Portal_C : UBP_SanctuaryPortal_MaterialComponent_BOGToStudy_C {
};

