// BlueprintGeneratedClass FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C
// Size: 0x28 (Inherited: 0x28)
struct UFL_NurturingFunctionLibary_C : UBlueprintFunctionLibrary {

	void GetAllAvailableTraitsForLoom(struct FGearItem GearItem, struct FName GearRarity, struct UObject* __WorldContext, int32_t& TotalAvailableTraits); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetAllAvailableTraitsForLoom // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void MoveCursorToCenterOfWidget(struct UWidget* Widget, struct UObject* __WorldContext); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.MoveCursorToCenterOfWidget // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetTotalAvailableTriats(struct FGearItem GearItem, struct UObject* __WorldContext, int32_t& TotalAvailableTraits); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetTotalAvailableTriats // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ToggleHideHUDForNurturingScreen(bool Hide, struct UObject* Provider, struct UObject* __WorldContext); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.ToggleHideHUDForNurturingScreen // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Get Creature Pregnancy Durations(struct UCreatureState* CreatureState, struct UObject* __WorldContext, struct FTimespan& TotalDuration, struct FTimespan& DurationRemaining); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.Get Creature Pregnancy Durations // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetIsUsingPlayerCamera(struct UObject* __WorldContext, bool& UsingPlayerCamera); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetIsUsingPlayerCamera // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Get Can View Creature Details(struct UCreatureState* CreatureState, struct UObject* __WorldContext, bool& CanMoveCreature, struct FString& ErrorMsgKey); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.Get Can View Creature Details // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void Get Can Summon Creature(struct UCreatureState* CreatureState, struct UObject* __WorldContext, bool& CanMoveCreature, struct FString& ErrorMsgKey); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.Get Can Summon Creature // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void GetTimeRemainingText(struct FTimespan TimeRemaining, struct UObject* __WorldContext, struct FText& TimeRemainingText); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetTimeRemainingText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void GetCreatureDisplayNameFromUIDName(struct FName CreatureUID, struct UObject* __WorldContext, struct FString& OutName, bool& OutIsLocalizationKey); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetCreatureDisplayNameFromUIDName // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCanMoveCreatureOutOfNurtureSpace(struct UCreatureState* CreatureState, struct UObject* __WorldContext, bool& CanMoveCreature, struct FString& ErrorMsgKey); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetCanMoveCreatureOutOfNurtureSpace // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void GetUnlockTextFromUnlockSource(struct FTransfigurationUnlockSource Unlock Source, struct UObject* __WorldContext, struct FText& Unlock Text); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetUnlockTextFromUnlockSource // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void GetUnbornCreatureIconTextureName(struct UCreatureDefinition* CreatureDefinition, struct UObject* __WorldContext, struct FString& IconTextureName); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetUnbornCreatureIconTextureName // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void SetTextToCreatureName(struct UCreatureState* CreatureState, struct UPhoenixTextBlock* PhoenixTextBlock, struct UObject* __WorldContext); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.SetTextToCreatureName // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCreatureIconTextureName(struct UCreatureState* CreatureState, struct UObject* __WorldContext, struct FString& IconTextureName); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetCreatureIconTextureName // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCreatureInventoryInfoString(struct FName InVariation, struct UObject* __WorldContext, struct FString& OutInfoString); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetCreatureInventoryInfoString // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCreatureInventoryButtonLegend(struct UObject* __WorldContext, struct FText& ButtonLegend); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetCreatureInventoryButtonLegend // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCreatureSpecies(struct FName InCreatureUID, struct UObject* __WorldContext, struct FString& CreatureSpecies); // Function FL_NurturingFunctionLibary.FL_NurturingFunctionLibary_C.GetCreatureSpecies // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
};

