// BlueprintGeneratedClass FL_VFX_DustRockFX.FL_VFX_DustRockFX_C
// Size: 0x28 (Inherited: 0x28)
struct UFL_VFX_DustRockFX_C : UBlueprintFunctionLibrary {

	void RockWhirlwind01Params(struct UNiagaraComponent* VFX_NS_RockWhirlwind01, int32_t EmissionAmount, float EmissionRateAdditional, float EmissionRadius, float EmissionHeight, float SystemHeightOffset, float RockScale, float GooScale, float AlphaErosion, float GravityScale, float SystemIntensity, float SystemScale, float VortexSpeedScale, bool UseCone, bool UseConeInverted, bool Activate, bool Deactivate, struct UObject* __WorldContext); // Function FL_VFX_DustRockFX.FL_VFX_DustRockFX_C.RockWhirlwind01Params // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void DustDebrisTunnel(struct UNiagaraComponent* VFX_NS_DustDebrisTunnel, struct FLinearColor DustCloudColor, float EmissionRateScale, float EmitterRadius, float FlipbookSpeedScale, float GravityScale, float LifetimeScale, float LimitedLoops, float SystemIntensity, float SystemOpacity, float SystemScale, float VelocityConeAngle, float VelocityScale, bool Activate, bool Deactivate, struct UObject* __WorldContext); // Function FL_VFX_DustRockFX.FL_VFX_DustRockFX_C.DustDebrisTunnel // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Debris Dust Fall 01Params(struct UNiagaraComponent* VFX_NS_RockDustBurst01, bool InitialBurst, struct FLinearColor DustColor, struct FVector EmissionArea, float EmissionRateDust, float EmissionRateRocks, float EmissionRateScale, float GravityScaleDust, float LifetimeScale, float LimitedLoops, float LoopDelay, float LoopLength, float RockGravityMultiply, float RockRotationScale, float RockScale, float RockScaleVariation, float RockSpinTime, float SystemIntensity, float SystemOpacity, float SystemScale, float VelocityAngle, float VelocityScale, float VelocityScaleRocks, bool UseCorrupted, bool Activate, bool Deactivate, struct UObject* __WorldContext); // Function FL_VFX_DustRockFX.FL_VFX_DustRockFX_C.Debris Dust Fall 01Params // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RockDustBurst01Params(struct UNiagaraComponent* VFX_NS_RockDustBurst01, struct FLinearColor DustColor, struct FVector EmissionArea, float EmissionLoops, float EmissionLoopsDelay, float EmissionRateScale, float EmissionTime, float GravityScaleRocks, float SystemIntensity, float SystemOpacity, float SystemScale, float VelocityAngle, float VelocityScale, bool Activate, bool Deactivate, struct UObject* __WorldContext); // Function FL_VFX_DustRockFX.FL_VFX_DustRockFX_C.RockDustBurst01Params // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
};

