// Class Hermes.HermesBPLibrary
// Size: 0x28 (Inherited: 0x28)
struct UHermesBPLibrary : UBlueprintFunctionLibrary {

	void HermesVectorDelegate__DelegateSignature(struct UObject* Caller, struct FVector& Vector); // DelegateFunction Hermes.HermesBPLibrary.HermesVectorDelegate__DelegateSignature // (Public|Delegate|HasOutParms|HasDefaults) // @ game+0x38a7480
	void HermesUnbind(struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesUnbind // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5ec80
	void HermesIntDelegate__DelegateSignature(struct UObject* Caller, int32_t int); // DelegateFunction Hermes.HermesBPLibrary.HermesIntDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
	void HermesHitResultDelegate__DelegateSignature(struct UObject* Caller, struct FHitResult& HitResult); // DelegateFunction Hermes.HermesBPLibrary.HermesHitResultDelegate__DelegateSignature // (Public|Delegate|HasOutParms) // @ game+0x38a7480
	void HermesGuidDelegate__DelegateSignature(struct UObject* Caller, struct FGuid& Guid); // DelegateFunction Hermes.HermesBPLibrary.HermesGuidDelegate__DelegateSignature // (Public|Delegate|HasOutParms|HasDefaults) // @ game+0x38a7480
	void HermesFTextDelegate__DelegateSignature(struct UObject* Caller, struct FText& Text); // DelegateFunction Hermes.HermesBPLibrary.HermesFTextDelegate__DelegateSignature // (Public|Delegate|HasOutParms) // @ game+0x38a7480
	void HermesFStringDelegate__DelegateSignature(struct UObject* Caller, struct FString String); // DelegateFunction Hermes.HermesBPLibrary.HermesFStringDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
	void HermesFNameDelegate__DelegateSignature(struct UObject* Caller, struct FName& String); // DelegateFunction Hermes.HermesBPLibrary.HermesFNameDelegate__DelegateSignature // (Public|Delegate|HasOutParms) // @ game+0x38a7480
	void HermesFloatDelegate__DelegateSignature(struct UObject* Caller, float float); // DelegateFunction Hermes.HermesBPLibrary.HermesFloatDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
	void HermesExecuteOwnedVector(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FVector& Vector); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedVector // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xf5eae0
	void HermesExecuteOwnedInt(struct FString Name, struct UObject* Owner, struct UObject* Caller, int32_t int); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedInt // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5e950
	void HermesExecuteOwnedHitResult(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FHitResult& HitResult); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedHitResult // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5e770
	void HermesExecuteOwnedGuid(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FGuid& Guid); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedGuid // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xf5e5b0
	void HermesExecuteOwnedFText(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FText& Text); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedFText // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5e240
	void HermesExecuteOwnedFString(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FString String); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedFString // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5e0a0
	void HermesExecuteOwnedFName(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FName& String); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedFName // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5def0
	void HermesExecuteOwnedFloat(struct FString Name, struct UObject* Owner, struct UObject* Caller, float float); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedFloat // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5e420
	void HermesExecuteOwnedEvent(struct FString Name, struct UObject* Owner, struct UObject* Caller); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedEvent // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5dd90
	void HermesExecuteOwnedDoubleInt(struct FString Name, struct UObject* Owner, struct UObject* Caller, int32_t int, int32_t Int2); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedDoubleInt // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5dbc0
	void HermesExecuteOwnedDoubleFString(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct FString String1, struct FString String2); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedDoubleFString // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5d9d0
	void HermesExecuteOwnedAActor(struct FString Name, struct UObject* Owner, struct UObject* Caller, struct AActor* Actor); // Function Hermes.HermesBPLibrary.HermesExecuteOwnedAActor // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5d840
	void HermesExecuteAllVector(struct FString Name, struct UObject* Caller, struct FVector& Vector); // Function Hermes.HermesBPLibrary.HermesExecuteAllVector // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xf5d6d0
	void HermesExecuteAllInt(struct FString Name, struct UObject* Caller, int32_t int); // Function Hermes.HermesBPLibrary.HermesExecuteAllInt // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5d570
	void HermesExecuteAllHitResult(struct FString Name, struct UObject* Caller, struct FHitResult& HitResult); // Function Hermes.HermesBPLibrary.HermesExecuteAllHitResult // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5d3d0
	void HermesExecuteAllGuid(struct FString Name, struct UObject* Caller, struct FGuid& Guid); // Function Hermes.HermesBPLibrary.HermesExecuteAllGuid // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xf5d260
	void HermesExecuteAllFText(struct FString Name, struct UObject* Caller, struct FText& Text); // Function Hermes.HermesBPLibrary.HermesExecuteAllFText // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5cf30
	void HermesExecuteAllFString(struct FString Name, struct UObject* Caller, struct FString String); // Function Hermes.HermesBPLibrary.HermesExecuteAllFString // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5cdc0
	void HermesExecuteAllFName(struct FString Name, struct UObject* Caller, struct FName& String); // Function Hermes.HermesBPLibrary.HermesExecuteAllFName // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5cc50
	void HermesExecuteAllFloat(struct FString Name, struct UObject* Caller, float float); // Function Hermes.HermesBPLibrary.HermesExecuteAllFloat // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5d0f0
	void HermesExecuteAllEvent(struct FString Name, struct UObject* Caller); // Function Hermes.HermesBPLibrary.HermesExecuteAllEvent // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5cb30
	void HermesExecuteAllDoubleInt(struct FString Name, struct UObject* Caller, int32_t Int1, int32_t Int2); // Function Hermes.HermesBPLibrary.HermesExecuteAllDoubleInt // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5c9a0
	void HermesExecuteAllDoubleFString(struct FString Name, struct UObject* Caller, struct FString String1, struct FString String2); // Function Hermes.HermesBPLibrary.HermesExecuteAllDoubleFString // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5c7e0
	void HermesExecuteAllAActor(struct FString Name, struct UObject* Caller, struct AActor* Actor); // Function Hermes.HermesBPLibrary.HermesExecuteAllAActor // (Final|Native|Static|Public|BlueprintCallable) // @ game+0xf5c680
	void HermesEventDelegate__DelegateSignature(struct UObject* Caller); // DelegateFunction Hermes.HermesBPLibrary.HermesEventDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
	void HermesDoubleIntDelegate__DelegateSignature(struct UObject* Caller, int32_t Int1, int32_t Int2); // DelegateFunction Hermes.HermesBPLibrary.HermesDoubleIntDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
	void HermesDoubleFStringDelegate__DelegateSignature(struct UObject* Caller, struct FString String1, struct FString String2); // DelegateFunction Hermes.HermesBPLibrary.HermesDoubleFStringDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
	void HermesBindVector(struct FDelegate Delegate_Vector, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindVector // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5c550
	void HermesBindInt(struct FDelegate Delegate_Int, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindInt // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5c420
	void HermesBindHitResult(struct FDelegate Delegate_HitResult, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindHitResult // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5c2f0
	void HermesBindGuid(struct FDelegate Delegate_Guid, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindGuid // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5c1c0
	void HermesBindFText(struct FDelegate Delegate_FText, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindFText // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5bf60
	void HermesBindFString(struct FDelegate Delegate_FString, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindFString // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5be30
	void HermesBindFName(struct FDelegate Delegate_FName, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindFName // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5bd00
	void HermesBindFloat(struct FDelegate Delegate_Float, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindFloat // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5c090
	void HermesBindEvent(struct FDelegate& Delegate_Event, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindEvent // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5bbc0
	void HermesBindDoubleInt(struct FDelegate Delegate_DoubleInt, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindDoubleInt // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5ba90
	void HermesBindDoubleFString(struct FDelegate Delegate_DoubleFString, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindDoubleFString // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5b960
	void HermesBindAActor(struct FDelegate Delegate_AActor, struct UObject* Owner, struct FHermesBPDelegateHandle& Handle); // Function Hermes.HermesBPLibrary.HermesBindAActor // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xf5b830
	void HermesAActorDelegate__DelegateSignature(struct UObject* Caller, struct AActor* Actor); // DelegateFunction Hermes.HermesBPLibrary.HermesAActorDelegate__DelegateSignature // (Public|Delegate) // @ game+0x38a7480
};

