// WidgetBlueprintGeneratedClass UI_BP_Settings_Display.UI_BP_Settings_Display_C
// Size: 0x6e4 (Inherited: 0x420)
struct UUI_BP_Settings_Display_C : UGraphicsSettingsWidget {
	struct FPointerToUberGraphFrame UberGraphFrame; // 0x420(0x08)
	struct UWidgetAnimation* showDetails; // 0x428(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_AntiAliasingMode; // 0x430(0x08)
	struct UUI_BP_MenuTextButton_C* btn_applySettings; // 0x438(0x08)
	struct UUI_BP_MenuTextButton_C* btn_calibration; // 0x440(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_chromaticAberration; // 0x448(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_DepthOfField; // 0x450(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_displayOptions; // 0x458(0x08)
	struct UUI_BP_SettingsSliderButton_C* btn_fieldOfView; // 0x460(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_FilmGrain; // 0x468(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_framegeneration; // 0x470(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_FrameRate; // 0x478(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_HDRCheckbox; // 0x480(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_motionBlur; // 0x488(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_nvidiaLatency; // 0x490(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_RenderingResolution; // 0x498(0x08)
	struct UUI_BP_MenuTextButton_C* btn_resetSettings; // 0x4a0(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_Resolution; // 0x4a8(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_selectedMonitor; // 0x4b0(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_selectGPU; // 0x4b8(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_UpscaleBrand; // 0x4c0(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_UpscaleMode; // 0x4c8(0x08)
	struct UUI_BP_SettingsSliderButton_C* btn_upscaleSharpness; // 0x4d0(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_VSync; // 0x4d8(0x08)
	struct UButton* DisabledFrameGenerationHoverButton; // 0x4e0(0x08)
	struct UButton* DisabledVSyncHoverButton; // 0x4e8(0x08)
	struct UUI_BP_SimpleScrollBox_C* displayScrollBox; // 0x4f0(0x08)
	struct UUI_BP_SettingsDetails_C* settingsDetails; // 0x4f8(0x08)
	struct TArray<struct FIntPoint> ResolutionArray; // 0x500(0x10)
	struct TArray<enum class EWindowMode> DisplayArray; // 0x510(0x10)
	float Min_FOVOffset_PC; // 0x520(0x04)
	float Max_FOVOffset_PC; // 0x524(0x04)
	float Min_FOVOffset_Console; // 0x528(0x04)
	float Max_FOVOffset_Console; // 0x52c(0x04)
	struct TArray<struct FString> ResolutionStringArray; // 0x530(0x10)
	struct USystemMenuWidget* ParentSettingsPage; // 0x540(0x08)
	struct TArray<struct FString> AvailableMonitors; // 0x548(0x10)
	float SelectedUpscaleSoftness; // 0x558(0x04)
	char pad_55C[0x4]; // 0x55c(0x04)
	struct TArray<struct FString> AvailableUpscaleMethodStrings; // 0x560(0x10)
	struct TMap<int32_t, struct FIntPoint> AvailableRenderingResolutions; // 0x570(0x50)
	struct TArray<struct FString> AvailableRenderingResolutionStrings; // 0x5c0(0x10)
	struct TArray<int32_t> ResolutionScales; // 0x5d0(0x10)
	struct TArray<struct FString> AvailableFrameRates; // 0x5e0(0x10)
	struct TArray<struct FString> AntiAliasingModeArray; // 0x5f0(0x10)
	struct TArray<struct FString> UpscaleBrandArray; // 0x600(0x10)
	struct TArray<struct FString> UpscaleModeArray; // 0x610(0x10)
	enum class EUpscaleMode UnconfirmedUpscaleMode; // 0x620(0x01)
	char pad_621[0x3]; // 0x621(0x03)
	struct FIntPoint UnconfirmedScreenResolution; // 0x624(0x08)
	float UnconfirmedUpscaleSharpness; // 0x62c(0x04)
	bool UnconfirmedEnableHDR; // 0x630(0x01)
	bool UnconfirmedEnableVSync; // 0x631(0x01)
	char pad_632[0x2]; // 0x632(0x02)
	float UnconfirmedMaxFrameRate; // 0x634(0x04)
	bool UnconfirmedEnableMotionBlur; // 0x638(0x01)
	bool UnconfirmedEnableDepthOfField; // 0x639(0x01)
	char pad_63A[0x2]; // 0x63a(0x02)
	float UnconfirmedRenderingResolutionPct; // 0x63c(0x04)
	bool UnconfirmedEnableChromaticAberration; // 0x640(0x01)
	bool UnconfirmedEnableFilmGrain; // 0x641(0x01)
	char pad_642[0x2]; // 0x642(0x02)
	float UnconfirmedFOVOffset; // 0x644(0x04)
	struct FString tooltipTitle; // 0x648(0x10)
	struct FString TooltipDescription; // 0x658(0x10)
	bool isButtonHovered; // 0x668(0x01)
	char pad_669[0x3]; // 0x669(0x03)
	float CurrentHoverTime; // 0x66c(0x04)
	float RequiredHoverTime; // 0x670(0x04)
	bool isDetailsShowing; // 0x674(0x01)
	char pad_675[0x3]; // 0x675(0x03)
	struct TArray<struct FGraphicsAdapterDesc> AvailableGPUs; // 0x678(0x10)
	int32_t LastConfirmedGPUSelection; // 0x688(0x04)
	int32_t UnconfirmedGPUSelection; // 0x68c(0x04)
	bool GPUSelectionChanged; // 0x690(0x01)
	enum class EAntiAliasingMode UnconfirmedAntiAliasingMode; // 0x691(0x01)
	char pad_692[0x6]; // 0x692(0x06)
	struct TArray<enum class EAntiAliasingMode> AntiAliasingModeValuesArray; // 0x698(0x10)
	struct TArray<enum class EUpscaleBrand> UpscaleBrandValuesArray; // 0x6a8(0x10)
	struct TArray<enum class EUpscaleMode> UpscaleModeValuesArray; // 0x6b8(0x10)
	bool UnconfirmedEnableFrameGeneration; // 0x6c8(0x01)
	char pad_6C9[0x7]; // 0x6c9(0x07)
	struct TArray<struct FNvidiaLatencyModeInfo> LatencyOptions; // 0x6d0(0x10)
	int32_t UnconfirmedNVidiaLatencyIndex; // 0x6e0(0x04)

	void GetAsyncWrapperRenderSize(struct FVector2D& RenderSize); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.GetAsyncWrapperRenderSize // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCurrentLatencyIndex(int32_t& LatencyIndex); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.GetCurrentLatencyIndex // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Convert FOVValue to Text(float FOVOffset, struct FText& FOVText); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.Convert FOVValue to Text // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void InitializeAllSettings(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.InitializeAllSettings // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnApplyAccepted(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.OnApplyAccepted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnUpscaleModeChanged(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.OnUpscaleModeChanged // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void UpdateDisplaySettings(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.UpdateDisplaySettings // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ShowTooltip(struct FString Title, struct FString Description); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.ShowTooltip // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnSettingsReverted(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.OnSettingsReverted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnSettingsApplied(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.OnSettingsApplied // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnOptionChanged(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.OnOptionChanged // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void LoadDefaults(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.LoadDefaults // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void HideTooltip(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.HideTooltip // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetFOVOffsetFromSliderValue(float Slider Value, float& FOV Offset); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.GetFOVOffsetFromSliderValue // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCurrentFOVSliderValue(float& SliderValue); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.GetCurrentFOVSliderValue // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ConditionallyDisableResolutionSelection(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.ConditionallyDisableResolutionSelection // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RefreshSelectGpuOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.RefreshSelectGpuOptions // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildSelectGpuOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildSelectGpuOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildWindowModeOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildWindowModeOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildAntiAliasingOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildAntiAliasingOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildLatencyOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildLatencyOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildUpscaleOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildUpscaleOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildUpscaleBrands(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildUpscaleBrands // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildResolutionOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildResolutionOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildRenderingResolutions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildRenderingResolutions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildMonitorOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildMonitorOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildFramerateOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildFramerateOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildDropDownOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BuildDropDownOptions // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void FetchLatencyOptions(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.FetchLatencyOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_FrameRate_K2Node_ComponentBoundEvent_2_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_FrameRate_K2Node_ComponentBoundEvent_2_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_motionBlur_K2Node_ComponentBoundEvent_5_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_motionBlur_K2Node_ComponentBoundEvent_5_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_VSync_K2Node_ComponentBoundEvent_17_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_VSync_K2Node_ComponentBoundEvent_17_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_fieldOfView_K2Node_ComponentBoundEvent_1_SettingsSliderChanged__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton, float NewValue); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_fieldOfView_K2Node_ComponentBoundEvent_1_SettingsSliderChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_displayOptions_K2Node_ComponentBoundEvent_18_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_displayOptions_K2Node_ComponentBoundEvent_18_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_Resolution_K2Node_ComponentBoundEvent_19_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_Resolution_K2Node_ComponentBoundEvent_19_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_FrameRate_K2Node_ComponentBoundEvent_24_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_FrameRate_K2Node_ComponentBoundEvent_24_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_fieldOfView_K2Node_ComponentBoundEvent_28_SettingsSliderHovered__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_fieldOfView_K2Node_ComponentBoundEvent_28_SettingsSliderHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_motionBlur_K2Node_ComponentBoundEvent_29_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_motionBlur_K2Node_ComponentBoundEvent_29_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_VSync_K2Node_ComponentBoundEvent_31_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_VSync_K2Node_ComponentBoundEvent_31_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_calibration_K2Node_ComponentBoundEvent_33_MenuTextButtonHovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_calibration_K2Node_ComponentBoundEvent_33_MenuTextButtonHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_35_MenuTextButtonHovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_35_MenuTextButtonHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_displayOptions_K2Node_ComponentBoundEvent_36_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_displayOptions_K2Node_ComponentBoundEvent_36_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_Resolution_K2Node_ComponentBoundEvent_37_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_Resolution_K2Node_ComponentBoundEvent_37_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_FrameRate_K2Node_ComponentBoundEvent_42_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_FrameRate_K2Node_ComponentBoundEvent_42_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_fieldOfView_K2Node_ComponentBoundEvent_46_SettingsSliderUnhovered__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_fieldOfView_K2Node_ComponentBoundEvent_46_SettingsSliderUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_motionBlur_K2Node_ComponentBoundEvent_47_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_motionBlur_K2Node_ComponentBoundEvent_47_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_VSync_K2Node_ComponentBoundEvent_49_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_VSync_K2Node_ComponentBoundEvent_49_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_calibration_K2Node_ComponentBoundEvent_51_MenuTextButtonUnhovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_calibration_K2Node_ComponentBoundEvent_51_MenuTextButtonUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_52_MenuTextButtonUnhovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_52_MenuTextButtonUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_selectedMonitor_K2Node_ComponentBoundEvent_0_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_selectedMonitor_K2Node_ComponentBoundEvent_0_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_upscaleSharpness_K2Node_ComponentBoundEvent_12_SettingsSliderHovered__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_upscaleSharpness_K2Node_ComponentBoundEvent_12_SettingsSliderHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_upscaleSharpness_K2Node_ComponentBoundEvent_13_SettingsSliderUnhovered__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_upscaleSharpness_K2Node_ComponentBoundEvent_13_SettingsSliderUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_selectedMonitor_K2Node_ComponentBoundEvent_14_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_selectedMonitor_K2Node_ComponentBoundEvent_14_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_selectedMonitor_K2Node_ComponentBoundEvent_16_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_selectedMonitor_K2Node_ComponentBoundEvent_16_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_calibration_K2Node_ComponentBoundEvent_4_MenuTextButtonClicked__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_calibration_K2Node_ComponentBoundEvent_4_MenuTextButtonClicked__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RenderingResolution_K2Node_ComponentBoundEvent_20_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_RenderingResolution_K2Node_ComponentBoundEvent_20_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RenderingResolution_K2Node_ComponentBoundEvent_21_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_RenderingResolution_K2Node_ComponentBoundEvent_21_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RenderingResolution_K2Node_ComponentBoundEvent_22_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_RenderingResolution_K2Node_ComponentBoundEvent_22_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_upscaleSharpness_K2Node_ComponentBoundEvent_9_SettingsSliderChanged__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton, float NewValue); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_upscaleSharpness_K2Node_ComponentBoundEvent_9_SettingsSliderChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_Resolution_K2Node_ComponentBoundEvent_7_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_Resolution_K2Node_ComponentBoundEvent_7_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_3_MenuTextButtonHovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_3_MenuTextButtonHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_30_MenuTextButtonUnhovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_30_MenuTextButtonUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void SyncDisplaySettings(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.SyncDisplaySettings // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_displayOptions_K2Node_ComponentBoundEvent_6_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_displayOptions_K2Node_ComponentBoundEvent_6_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_31_MenuTextButtonClicked__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_31_MenuTextButtonClicked__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void Construct(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.Construct // (BlueprintCosmetic|Event|Public|BlueprintEvent) // @ game+0x38a7480
	void UINeedsUpdate(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.UINeedsUpdate // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_32_MenuTextButtonClicked__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_32_MenuTextButtonClicked__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_34_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_34_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_38_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_38_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_39_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_39_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_HDRCheckbox_K2Node_ComponentBoundEvent_23_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_HDRCheckbox_K2Node_ComponentBoundEvent_23_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_HDRCheckbox_K2Node_ComponentBoundEvent_26_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_HDRCheckbox_K2Node_ComponentBoundEvent_26_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_HDRCheckbox_K2Node_ComponentBoundEvent_15_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_HDRCheckbox_K2Node_ComponentBoundEvent_15_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void LeaveFromPage(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.LeaveFromPage // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_K2Node_ComponentBoundEvent_8_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_K2Node_ComponentBoundEvent_8_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_K2Node_ComponentBoundEvent_10_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_K2Node_ComponentBoundEvent_10_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_K2Node_ComponentBoundEvent_40_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_K2Node_ComponentBoundEvent_40_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_10_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_10_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_FrameRate_K2Node_ComponentBoundEvent_27_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_FrameRate_K2Node_ComponentBoundEvent_27_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void Initialize(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.Initialize // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_41_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_41_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_43_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_43_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_44_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_44_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void SetParent(struct UUserWidget* Parent); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.SetParent // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_1_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_1_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void InEditorPostConstruct(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.InEditorPostConstruct // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_48_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_48_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_53_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_53_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_1_K2Node_ComponentBoundEvent_50_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_chromaticAberration_1_K2Node_ComponentBoundEvent_50_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_DepthOfField_K2Node_ComponentBoundEvent_57_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_DepthOfField_K2Node_ComponentBoundEvent_57_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_DepthOfField_K2Node_ComponentBoundEvent_55_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_DepthOfField_K2Node_ComponentBoundEvent_55_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_FilmGrain_K2Node_ComponentBoundEvent_54_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_FilmGrain_K2Node_ComponentBoundEvent_54_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_FilmGrain_K2Node_ComponentBoundEvent_58_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_FilmGrain_K2Node_ComponentBoundEvent_58_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_FilmGrain_K2Node_ComponentBoundEvent_60_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_FilmGrain_K2Node_ComponentBoundEvent_60_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_upscaleSharpness_K2Node_ComponentBoundEvent_56_SettingsSliderFinished__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton, float EndValue); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_upscaleSharpness_K2Node_ComponentBoundEvent_56_SettingsSliderFinished__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_fieldOfView_K2Node_ComponentBoundEvent_61_SettingsSliderFinished__DelegateSignature(struct UUI_BP_SettingsSliderButton_C* SliderButton, float EndValue); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_fieldOfView_K2Node_ComponentBoundEvent_61_SettingsSliderFinished__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_displayOptions_K2Node_ComponentBoundEvent_59_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_displayOptions_K2Node_ComponentBoundEvent_59_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectedMonitor_K2Node_ComponentBoundEvent_62_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectedMonitor_K2Node_ComponentBoundEvent_62_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_Resolution_K2Node_ComponentBoundEvent_63_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_Resolution_K2Node_ComponentBoundEvent_63_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_RenderingResolution_K2Node_ComponentBoundEvent_64_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_RenderingResolution_K2Node_ComponentBoundEvent_64_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_65_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_65_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_66_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleMode_K2Node_ComponentBoundEvent_66_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_FrameRate_K2Node_ComponentBoundEvent_67_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_FrameRate_K2Node_ComponentBoundEvent_67_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_68_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_68_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void OnLegendItemHoldEnd(struct ULegendItem* LegendItem, bool HoldWasCompleted); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.OnLegendItemHoldEnd // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_displayOptions_K2Node_ComponentBoundEvent_69_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_displayOptions_K2Node_ComponentBoundEvent_69_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectedMonitor_K2Node_ComponentBoundEvent_70_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectedMonitor_K2Node_ComponentBoundEvent_70_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_Resolution_K2Node_ComponentBoundEvent_71_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_Resolution_K2Node_ComponentBoundEvent_71_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_RenderingResolution_K2Node_ComponentBoundEvent_72_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_RenderingResolution_K2Node_ComponentBoundEvent_72_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_73_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_AntiAliasingMode_K2Node_ComponentBoundEvent_73_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_74_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_selectGPU_K2Node_ComponentBoundEvent_74_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_75_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_75_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_76_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_76_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_77_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_77_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_78_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_78_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_79_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_UpscaleBrand_K2Node_ComponentBoundEvent_79_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void RefreshUpscaleModeAA(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.RefreshUpscaleModeAA // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_framegeneration_K2Node_ComponentBoundEvent_1_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_framegeneration_K2Node_ComponentBoundEvent_1_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_framegeneration_K2Node_ComponentBoundEvent_2_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_framegeneration_K2Node_ComponentBoundEvent_2_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_framegeneration_K2Node_ComponentBoundEvent_0_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_framegeneration_K2Node_ComponentBoundEvent_0_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_DisabledFrameGenerationHoverButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_DisabledFrameGenerationHoverButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_DisabledFrameGenerationHoverButton_K2Node_ComponentBoundEvent_83_OnButtonHoverEvent__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_DisabledFrameGenerationHoverButton_K2Node_ComponentBoundEvent_83_OnButtonHoverEvent__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_DisabledVSyncHoverButton_K2Node_ComponentBoundEvent_85_OnButtonHoverEvent__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_DisabledVSyncHoverButton_K2Node_ComponentBoundEvent_85_OnButtonHoverEvent__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_DisabledVSyncHoverButton_K2Node_ComponentBoundEvent_86_OnButtonHoverEvent__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_DisabledVSyncHoverButton_K2Node_ComponentBoundEvent_86_OnButtonHoverEvent__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_87_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_87_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_88_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_88_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_89_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_89_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_90_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_90_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_91_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.BndEvt__UI_BP_Settings_Display_btn_nvidiaLatency_K2Node_ComponentBoundEvent_91_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void ExecuteUbergraph_UI_BP_Settings_Display(int32_t EntryPoint); // Function UI_BP_Settings_Display.UI_BP_Settings_Display_C.ExecuteUbergraph_UI_BP_Settings_Display // (Final|UbergraphFunction|HasDefaults) // @ game+0x38a7480
};

