// WidgetBlueprintGeneratedClass UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C
// Size: 0x584 (Inherited: 0x420)
struct UUI_BP_Settings_Graphics_C : UGraphicsSettingsWidget {
	struct FPointerToUberGraphFrame UberGraphFrame; // 0x420(0x08)
	struct UWidgetAnimation* showDetails; // 0x428(0x08)
	struct UUI_BP_MenuTextButton_C* btn_applySettings; // 0x430(0x08)
	struct UUI_BP_MenuTextButton_C* btn_benchmark; // 0x438(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_effectsQuality; // 0x440(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_fogQuality; // 0x448(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_foilageQuality; // 0x450(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_globalQuality; // 0x458(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_materialQuality; // 0x460(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_populationQuality; // 0x468(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_postProcessQuality; // 0x470(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_RaytracingAO; // 0x478(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_raytracingQuality; // 0x480(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_RaytracingReflections; // 0x488(0x08)
	struct UUI_BP_SettingsCheckboxButton_C* btn_RaytracingShadows; // 0x490(0x08)
	struct UUI_BP_MenuTextButton_C* btn_resetSettings; // 0x498(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_shadowQuality; // 0x4a0(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_skyQuality; // 0x4a8(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_textureQuality; // 0x4b0(0x08)
	struct UUI_BP_SettingsDropDownButton_C* btn_viewDistance; // 0x4b8(0x08)
	struct UUI_BP_SettingsDetails_C* detailsPanel; // 0x4c0(0x08)
	struct UUI_BP_SimpleScrollBox_C* graphicsScrollBox; // 0x4c8(0x08)
	struct TArray<struct FIntPoint> ResolutionArray; // 0x4d0(0x10)
	struct TArray<enum class EWindowMode> DisplayArray; // 0x4e0(0x10)
	struct USystemMenuWidget* ParentSettingsPage; // 0x4f0(0x08)
	int32_t LastConfirmedEffectsQuality; // 0x4f8(0x04)
	int32_t UnconfirmedEffectsQuality; // 0x4fc(0x04)
	int32_t LastConfirmedFoliageQuality; // 0x500(0x04)
	int32_t UnconfirmedFoliageQuality; // 0x504(0x04)
	int32_t LastConfirmedPostProcessQuality; // 0x508(0x04)
	int32_t UnconfirmedPostProcessQuality; // 0x50c(0x04)
	int32_t LastConfirmedShadowQuality; // 0x510(0x04)
	int32_t UnconfirmedShadowQuality; // 0x514(0x04)
	int32_t LastConfirmedTextureQuality; // 0x518(0x04)
	int32_t UnconfirmedTextureQuality; // 0x51c(0x04)
	int32_t LastConfirmedViewDistanceQuality; // 0x520(0x04)
	int32_t UnconfirmedViewDistanceQuality; // 0x524(0x04)
	bool isDetailsShowing; // 0x528(0x01)
	bool LastConfirmedRayTracingAO; // 0x529(0x01)
	bool LastConfirmedRayTracingReflections; // 0x52a(0x01)
	bool LastConfirmedRayTracingShadows; // 0x52b(0x01)
	bool RequiresConfirm; // 0x52c(0x01)
	bool UnconfirmedRayTracingAO; // 0x52d(0x01)
	bool UnconfirmedRayTracingReflections; // 0x52e(0x01)
	bool UnconfirmedRayTracingShadows; // 0x52f(0x01)
	struct FString TooltipDescription; // 0x530(0x10)
	struct FString tooltipTitle; // 0x540(0x10)
	float CurrentHoverTime; // 0x550(0x04)
	float RequiredHoverTime; // 0x554(0x04)
	bool RaytraceActiveStateChanged; // 0x558(0x01)
	bool PlayUltraSettingsAudio; // 0x559(0x01)
	char pad_55A[0x2]; // 0x55a(0x02)
	int32_t LastConfirmedMaterialQuality; // 0x55c(0x04)
	int32_t UnconfirmedMaterialQuality; // 0x560(0x04)
	int32_t UnconfirmedFogQuality; // 0x564(0x04)
	int32_t LastConfirmedFogQuality; // 0x568(0x04)
	int32_t UnconfirmedSkyQuality; // 0x56c(0x04)
	int32_t LastConfirmedSkyQuality; // 0x570(0x04)
	int32_t UnconfirmedPopulationQuality; // 0x574(0x04)
	int32_t LastPopulationQuality; // 0x578(0x04)
	int32_t UnconfirmedRaytracingQuality; // 0x57c(0x04)
	int32_t LastConfirmedRaytracingQuality; // 0x580(0x04)

	void GetAsyncWrapperRenderSize(struct FVector2D& RenderSize); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.GetAsyncWrapperRenderSize // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	bool Get_btn_raytracingQuality_bIsEnabled_1(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.Get_btn_raytracingQuality_bIsEnabled_1 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void AreAnySettingsBetterThanRecommended(bool& IsBetterThanRecommended); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.AreAnySettingsBetterThanRecommended // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void AreConfirmedLessThanOrEqualRecommended(bool& IsLessThanOrEqualRecommended); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.AreConfirmedLessThanOrEqualRecommended // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RevertChanges(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.RevertChanges // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Handle Settings Dirty(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.Handle Settings Dirty // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ConfirmQualitySettings(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.ConfirmQualitySettings // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RebuildGlobalQualityOptions(int32_t OptionalIndex); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.RebuildGlobalQualityOptions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void RefreshQualitySettings(int32_t OptionalIndex); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.RefreshQualitySettings // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void HideTooltip(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.HideTooltip // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ShowTooltip(struct FString Title, struct FString Desc); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.ShowTooltip // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildQualitySettings(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BuildQualitySettings // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildRaytracingOptions(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BuildRaytracingOptions // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildDropDownOptions(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BuildDropDownOptions // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnSettingsConfirmed(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.OnSettingsConfirmed // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnGlobalPresetChanged(int32_t SelectedQualityIndex); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.OnGlobalPresetChanged // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void AreSettingsRecommended(bool& IsRecommended); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.AreSettingsRecommended // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void AreSettingsSingleValue(bool& IsSingle); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.AreSettingsSingleValue // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_globalQuality_K2Node_ComponentBoundEvent_1_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_globalQuality_K2Node_ComponentBoundEvent_1_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_viewDistance_K2Node_ComponentBoundEvent_14_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_viewDistance_K2Node_ComponentBoundEvent_14_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_globalQuality_K2Node_ComponentBoundEvent_6_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_globalQuality_K2Node_ComponentBoundEvent_6_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_globalQuality_K2Node_ComponentBoundEvent_7_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_globalQuality_K2Node_ComponentBoundEvent_7_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_effectsQuality_K2Node_ComponentBoundEvent_21_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_effectsQuality_K2Node_ComponentBoundEvent_21_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_foilageQuality_K2Node_ComponentBoundEvent_22_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_foilageQuality_K2Node_ComponentBoundEvent_22_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_postProcessQuality_K2Node_ComponentBoundEvent_23_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_postProcessQuality_K2Node_ComponentBoundEvent_23_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_shadowQuality_K2Node_ComponentBoundEvent_25_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_shadowQuality_K2Node_ComponentBoundEvent_25_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_textureQuality_K2Node_ComponentBoundEvent_26_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_textureQuality_K2Node_ComponentBoundEvent_26_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_viewDistance_K2Node_ComponentBoundEvent_27_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_viewDistance_K2Node_ComponentBoundEvent_27_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_effectsQuality_K2Node_ComponentBoundEvent_10_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_effectsQuality_K2Node_ComponentBoundEvent_10_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_foilageQuality_K2Node_ComponentBoundEvent_11_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_foilageQuality_K2Node_ComponentBoundEvent_11_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_postProcessQuality_K2Node_ComponentBoundEvent_12_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_postProcessQuality_K2Node_ComponentBoundEvent_12_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_shadowQuality_K2Node_ComponentBoundEvent_13_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_shadowQuality_K2Node_ComponentBoundEvent_13_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_textureQuality_K2Node_ComponentBoundEvent_14_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_textureQuality_K2Node_ComponentBoundEvent_14_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_textureQuality_K2Node_ComponentBoundEvent_13_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_textureQuality_K2Node_ComponentBoundEvent_13_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingReflections_K2Node_ComponentBoundEvent_15_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingReflections_K2Node_ComponentBoundEvent_15_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingShadows_K2Node_ComponentBoundEvent_17_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingShadows_K2Node_ComponentBoundEvent_17_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingAO_K2Node_ComponentBoundEvent_18_SettingsCheckmarkPressed__DelegateSignature(bool IsChecked, struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingAO_K2Node_ComponentBoundEvent_18_SettingsCheckmarkPressed__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_shadowQuality_K2Node_ComponentBoundEvent_12_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_shadowQuality_K2Node_ComponentBoundEvent_12_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_viewDistance_K2Node_ComponentBoundEvent_19_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_viewDistance_K2Node_ComponentBoundEvent_19_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingReflections_K2Node_ComponentBoundEvent_28_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingReflections_K2Node_ComponentBoundEvent_28_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingShadows_K2Node_ComponentBoundEvent_29_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingShadows_K2Node_ComponentBoundEvent_29_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingAO_K2Node_ComponentBoundEvent_30_ToggleHovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingAO_K2Node_ComponentBoundEvent_30_ToggleHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingAO_K2Node_ComponentBoundEvent_31_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingAO_K2Node_ComponentBoundEvent_31_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingShadows_K2Node_ComponentBoundEvent_32_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingShadows_K2Node_ComponentBoundEvent_32_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_RaytracingReflections_K2Node_ComponentBoundEvent_33_ToggleUnhovered__DelegateSignature(struct UUI_BP_SettingsCheckboxButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_RaytracingReflections_K2Node_ComponentBoundEvent_33_ToggleUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_benchmark_K2Node_ComponentBoundEvent_2_MenuTextButtonHovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_benchmark_K2Node_ComponentBoundEvent_2_MenuTextButtonHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_benchmark_K2Node_ComponentBoundEvent_16_MenuTextButtonUnhovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_benchmark_K2Node_ComponentBoundEvent_16_MenuTextButtonUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_benchmark_K2Node_ComponentBoundEvent_37_MenuTextButtonClicked__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_benchmark_K2Node_ComponentBoundEvent_37_MenuTextButtonClicked__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_38_MenuTextButtonHovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_38_MenuTextButtonHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_postProcessQuality_K2Node_ComponentBoundEvent_11_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_postProcessQuality_K2Node_ComponentBoundEvent_11_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_39_MenuTextButtonUnhovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_39_MenuTextButtonUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_0_MenuTextButtonClicked__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_applySettings_K2Node_ComponentBoundEvent_0_MenuTextButtonClicked__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_foilageQuality_K2Node_ComponentBoundEvent_10_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_foilageQuality_K2Node_ComponentBoundEvent_10_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_effectsQuality_K2Node_ComponentBoundEvent_9_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_effectsQuality_K2Node_ComponentBoundEvent_9_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_41_MenuTextButtonHovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_41_MenuTextButtonHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_42_MenuTextButtonUnhovered__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_42_MenuTextButtonUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_4_MenuTextButtonClicked__DelegateSignature(struct UUI_BP_MenuTextButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__btn_resetSettings_K2Node_ComponentBoundEvent_4_MenuTextButtonClicked__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void Construct(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.Construct // (BlueprintCosmetic|Event|Public|BlueprintEvent) // @ game+0x38a7480
	void BenchmarkPopupDismissed(struct UPopupScreen* PopupScreen, int32_t CompletionActionIndex); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BenchmarkPopupDismissed // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BenchmarkCompleteDismissed(struct UPopupScreen* PopupScreen, int32_t CompletionActionIndex); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BenchmarkCompleteDismissed // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void LeaveFromPage(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.LeaveFromPage // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_32_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_32_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_34_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_34_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_35_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_35_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_postProcessQuality_K2Node_ComponentBoundEvent_36_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_postProcessQuality_K2Node_ComponentBoundEvent_36_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_shadowQuality_K2Node_ComponentBoundEvent_40_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_shadowQuality_K2Node_ComponentBoundEvent_40_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_textureQuality_K2Node_ComponentBoundEvent_43_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_textureQuality_K2Node_ComponentBoundEvent_43_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_viewDistance_K2Node_ComponentBoundEvent_44_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_viewDistance_K2Node_ComponentBoundEvent_44_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void UINeedsUpdate(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.UINeedsUpdate // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_foilageQuality_K2Node_ComponentBoundEvent_45_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_foilageQuality_K2Node_ComponentBoundEvent_45_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_5_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_5_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_24_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_24_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_47_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_47_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_49_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_49_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_50_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_volumetricsQuality_K2Node_ComponentBoundEvent_50_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_8_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_8_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_20_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_20_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_48_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_48_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_52_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_52_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void Initialize(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.Initialize // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_globalQuality_K2Node_ComponentBoundEvent_9_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_globalQuality_K2Node_ComponentBoundEvent_9_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_effectsQuality_K2Node_ComponentBoundEvent_46_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_effectsQuality_K2Node_ComponentBoundEvent_46_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_51_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_materialQuality_K2Node_ComponentBoundEvent_51_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_fogQuality_K2Node_ComponentBoundEvent_53_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_fogQuality_K2Node_ComponentBoundEvent_53_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_60_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_skyQuality_K2Node_ComponentBoundEvent_60_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_foilageQuality_K2Node_ComponentBoundEvent_61_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_foilageQuality_K2Node_ComponentBoundEvent_61_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_postProcessQuality_K2Node_ComponentBoundEvent_62_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_postProcessQuality_K2Node_ComponentBoundEvent_62_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_shadowQuality_K2Node_ComponentBoundEvent_63_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_shadowQuality_K2Node_ComponentBoundEvent_63_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_textureQuality_K2Node_ComponentBoundEvent_64_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_textureQuality_K2Node_ComponentBoundEvent_64_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_viewDistance_K2Node_ComponentBoundEvent_65_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_viewDistance_K2Node_ComponentBoundEvent_65_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void SetParent(struct UUserWidget* Parent); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.SetParent // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void OnLegendItemHoldEnd(struct ULegendItem* LegendItem, bool HoldWasCompleted); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.OnLegendItemHoldEnd // (Event|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void ApplySettingsAndConfirm(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.ApplySettingsAndConfirm // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_66_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_66_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_67_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_67_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_68_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_68_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_69_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_69_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_70_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_populationQuality_K2Node_ComponentBoundEvent_70_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void InEditorPostConstruct(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.InEditorPostConstruct // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_globalQuality_K2Node_ComponentBoundEvent_71_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_globalQuality_K2Node_ComponentBoundEvent_71_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_effectsQuality_K2Node_ComponentBoundEvent_72_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_effectsQuality_K2Node_ComponentBoundEvent_72_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void ConfirmedApply(struct UPopupScreen* PopupScreen, int32_t CompletionActionIndex); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.ConfirmedApply // (BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_74_DropDownOptionChanged__DelegateSignature(int32_t NewOptionIndex, struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_74_DropDownOptionChanged__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_78_DropdownHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_78_DropdownHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_80_DropdownUnhovered__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_80_DropdownUnhovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_84_DropdownOpened__DelegateSignature(); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_84_DropdownOpened__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_86_DropDownOptionHovered__DelegateSignature(struct UUI_BP_SettingsDropDownButton_C* Button, struct FString HoveredItemString); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.BndEvt__UI_BP_Settings_Graphics_btn_raytracingQuality_K2Node_ComponentBoundEvent_86_DropDownOptionHovered__DelegateSignature // (BlueprintEvent) // @ game+0x38a7480
	void ExecuteUbergraph_UI_BP_Settings_Graphics(int32_t EntryPoint); // Function UI_BP_Settings_Graphics.UI_BP_Settings_Graphics_C.ExecuteUbergraph_UI_BP_Settings_Graphics // (Final|UbergraphFunction|HasDefaults) // @ game+0x38a7480
};

