// BlueprintGeneratedClass UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UUI_BP_InventoryFunctionLibrary_C : UBlueprintFunctionLibrary {

	void GetGearItemStats(struct FGearItemID GearItemID, struct UObject* __WorldContext, int32_t& OffenseStat, int32_t& DefenseStat); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.GetGearItemStats // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetRarityColorTag(struct FName RarityTier, struct UObject* __WorldContext, struct FDataTableRowHandle& ColorTag); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.GetRarityColorTag // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Get Inventory Count(struct AActor* InActor, struct UObject* __WorldContext, int32_t& ReturnCount); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.Get Inventory Count // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetGearTooltipInfo(struct FGearItemID GearItemID, struct UObject* __WorldContext, struct FString& Title, struct FString& Description, struct FString& Quality, struct FName& Rarity, int32_t& SellPrice, bool& Sellable); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.GetGearTooltipInfo // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void BuildDefaultNonExpandContent(struct FName ItemName, struct FName Variation, struct UObject* __WorldContext, struct UUserWidget*& Content); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.BuildDefaultNonExpandContent // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void BuildDefaultTooltipContent(struct FName ItemName, struct FName Variation, struct UObject* __WorldContext, struct UUserWidget*& TooltipContent); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.BuildDefaultTooltipContent // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void BuildInventoryTooltip(struct UUI_BP_InventoryIconButton_C* Button, struct TArray<struct FLegendItemData>& Legend, struct UUserWidget* Content, struct UUserWidget* NonExpandContent, struct UObject* __WorldContext); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.BuildInventoryTooltip // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void LootItemsFromActor(struct AActor* Container, struct UObject* __WorldContext); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.LootItemsFromActor // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void IFL Transfer to Inventory(struct FInventoryResult InvResult, struct UObject* __WorldContext, bool& Success); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.IFL Transfer to Inventory // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void CanPerformTransfer(struct FName FromCharacterID, struct FName Item, struct FName ToCharacterID, int32_t howMany, struct FName FromHolderID, struct FName ToHolderID, struct FName Variation, struct UObject* __WorldContext, bool& CanTransfer); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.CanPerformTransfer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x38a7480
	void UIUpdateItem(struct UUserWidget* Button, struct UObject* __WorldContext); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.UIUpdateItem // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void UpdateInventoryIconFromInventoryResult(struct UUserWidget* Button, struct FInventoryResult InventoryItem, float Modifier, struct UObject* __WorldContext); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.UpdateInventoryIconFromInventoryResult // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void Transfer Item(struct FName FromCharacterID, struct FName Item, struct FName ToCharacterID, int32_t howMany, enum class EInventoryChangeReason Reason, struct FName FromHolderID, struct FName ToHolderID, bool SuppressHUDNotification, struct FName Variation, bool IsUnique, struct UObject* __WorldContext, bool& Success); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.Transfer Item // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetItemCount(struct FName CharacterID, struct FName ItemId, struct FName HolderID, struct FName Variation, struct UObject* __WorldContext, int32_t& Count); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.GetItemCount // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetMoney(struct FName CharacterID, struct UObject* __WorldContext, int32_t& Money); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.GetMoney // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
	void GetCharacterInventory(struct FName CharacterID, struct FName Category, struct FName HolderID, bool SkipLockedItems, struct UObject* __WorldContext, struct TArray<struct FInventoryResult>& Inventory); // Function UI_BP_InventoryFunctionLibrary.UI_BP_InventoryFunctionLibrary_C.GetCharacterInventory // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x38a7480
};

